title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: BInary Wizards
github_username: SortingMiniProject
github_repo: "BinaryWizards"
baseurl: "/BinaryWizards"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/EdwinKuttappi"}
    - { platform: github, user_url: "https://github.com/yuricoder07"}
    - { platform: github, user_url: "https://github.com/VINERAJ"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
